# Generated by Django 3.2.4 on 2021-06-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Image', models.FileField(upload_to='images')),
                ('Description', models.CharField(max_length=500)),
                ('Download', models.FileField(upload_to='apps')),
            ],
        ),
    ]
